version: "3.8"

services:

  database:
    container_name: database
    image: library/postgres:13.0-alpine
    env_file:
      - ./.env.db
    networks:
      - client-server-nginx

  server:
    container_name: server
    build:
      context: ./backend
    command: /start.sh
    volumes:
      - .:/code
      - django-static:/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - client-server-nginx

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - django-static:/code/staticfiles
    networks:
      - client-server-nginx

volumes:
  django-static:

networks:
  client-server-nginx:
    driver: bridge
